define([], function() {
	return {
		// Text
		TEXT_KEYUP: 'TEXT_KEYUP',
		TEXT_CLICK: 'TEXT_CLICK',

		// TextLength
		TEXT_LENGTH_UPDATE: 'TEXT_LENGTH_UPDATE',
		TEXT_LENGTH_ERROR: 'TEXT_LENGTH_ERROR',
		TEXT_LENGTH_OK: 'TEXT_LENGTH_OK',

		// Button
		BUTTON_CLICK: 'BUTTON_CLICK',

		// Option
		SELECT_OPTION: 'SELECT_OPTION',

		// TimeOptions
		SELECT_HOUR: 'SELECT_HOUR',
		SELECT_MINUTE: 'SELECT_MINUTE',
		SELECT_SECOND: 'SELECT_SECOND',

		// Select

		// Search

		// CheckboxGroup

		// RadioboxGroup

		// Pagination
		PAGINATION_CHANGE_PAGE: 'PAGINATION_CHANGE_PAGE',

		// Modal
		MODAL_CONFIRM: 'MODAL_CONFIRM',

		// MultiSelect

		// Tab
		TAB_CHANGE: 'TAB_CHANGE',

		// Calendar
		CALENDAR_SELECT_DATE: 'CALENDAR_SELECT_DATE',

		// Hover
		HOVER_SHOW: 'HOVER_SHOW',
		HOVER_HIDE: 'HOVER_HIDE',

		// Other
		CLICK_OUTSIDE: 'CLICK_OUTSIDE',
	}

})

